server:
  error:
    include-stacktrace: on_trace_param
  port: 8084
  servlet:
    context-path: /api/

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: always
    job:
      #Disable batch job's auto start
      enabled: false
  resources:
    chain:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  mail:
    host: email-smtp.sa-east-1.amazonaws.com
    password: BCa7g75XoKPoH65Pu8CL8u5CMDaXH4kjdyBAOOFryVVk
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: AKIAVEETHJ3RMC46IWUI

aws:
  access_key_id:
  secret_access_key:

logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

s3:
  bucket: cadeira-spring-react
  region: sa-east-1

sas:
  from: rodrigo.2018150572@unicap.br
  from-name: Valid Usability Assessment

security:
  jwt-expiration: 120
  jwt-sign-key: n2r5u7x!A%D*G-KaPdSgVkYp3s6v9y/B?E(H+MbQeThWmZq4t7w!z%C&F)J@NcRf